#-----------------------------------------------------------------------
# File: grade-submission-api-pod.yaml
#
# Author: Emmanuel Taylor
# Created: June 30, 2025
# Modified: June 30, 2025
#
# Description:
# Kubernetes Pod definition for the grade-submission-api application.
# 
# This Pod runs one container:
# - The main backend API service (grade-submission-api)
#
# The Pod is labeled for backend identification and can be targeted by
# services or policies. Resources are constrained for controlled CPU and
# memory usage.
#-----------------------------------------------------------------------

apiVersion: v1
kind: Pod
metadata:
  name: grade-submission-api
  namespace: grade-submission
  labels:
    app.kubernetes.io/name: grade-submission
    app.kubernetes.io/component: backend
    app.kubernetes.io/instance: grade-submission-api
spec:
  containers:
  - name: grade-submission-api
    image: rslim087/kubernetes-course-grade-submission-api:stateless
    resources:
      requests:
        memory: "128Mi"
        cpu: "128m"
      limits:
        memory: "128Mi"
    ports:
      - containerPort: 3000
