#-----------------------------------------------------------------------
# File: grade-submission-portal-pod.yaml
#
# Author: Emmanuel Taylor
# Created: June 30, 2025
# Modified: June 30, 2025
#
# Description:
# Kubernetes Pod definition for the grade-submission-portal application.
# 
# This Pod runs one container:
# - The main frontend service (grade-submission-portal)
#
# The Pod is labeled for frontend identification and can be targeted by
# services or policies. Resources are constrained for controlled CPU and
# memory usage.
#-----------------------------------------------------------------------

apiVersion: v1
kind: Pod
metadata:
  name: grade-submission-portal
  namespace: grade-submission
  labels:
    app.kubernetes.io/name: grade-submission
    app.kubernetes.io/component: frontend
    app.kubernetes.io/instance: grade-submission-portal
spec:
  containers:
  - name: grade-submission-portal
    image: rslim087/kubernetes-course-grade-submission-portal
    env:
      - name: GRADE_SERVICE_HOST
        value: grade-submission-api
    resources:
      requests:
        memory: "128Mi"
        cpu: "200m"
      limits:
        memory: "128Mi"
    ports:
      - containerPort: 5001