# ------------------------------------------------------------------------------
# File: kong-secret.yaml
#
# Author: Emmanuel Taylor
# Created: July 24, 2025
# Modified: July 24, 2025
#
# Description:
# Kubernetes Secret containing an API key credential for a KongConsumer.
#
# This Secret:
# - Stores a key-auth credential used to authenticate a consumer via Kong.
# - Must be labeled and structured according to Kong’s credential plugin requirements.
# - Is referenced by the KongConsumer `grade-submission-consumer`.
# - Should contain the desired API key value in plain text using `stringData`.
# ------------------------------------------------------------------------------

apiVersion: v1
kind: Secret
metadata:
 name: user1-apikey                # Must match name referenced in KongConsumer.
 namespace: grade-demo             # Namespace that this secret is deployed in.
 labels:
   konghq.com/credential: key-auth # Required label for Kong to recognize this as key-auth.
type: Opaque
stringData:
 kongCredType: key-auth            # Specifies the type of plugin this credential applies.
 key: your-secret-key              # The API Key value.